# Site settings
email:
  id: contactme@rutvora.com
  show_on_home: true
  show_in_contact: true
title: Rut Vora
description: >
  MS Computer Science Student at the University of British Columbia, Vancouver. <br />
  Research Assistant in Systopia, currently working on mitigating network Sidechannel attacks.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Rut Vora
street_address:
city:
state:
zip_code:
country:
phone:

icon: fa-r # Font Awesome class for your site's icon
remote_theme: andrewbanchich/dimension-jekyll-theme

# Email show config

# Research Links
orcid:
  url: https://orcid.org/0000-0001-5064-1760
  show_on_home: true
  show_in_contact: false
googlescholar:
  url: https://scholar.google.com/citations?user=gB4ZP1MAAAAJ
  show_on_home: true
  show_in_contact: false
researchgate:
  url: https://www.researchgate.net/profile/Rut-Vora
  show_on_home: true
  show_in_contact: false

# Work Links
github:
  url: https://www.github.com/rutvora
  show_on_home: true
  show_in_contact: false
gitlab:
  url:
  show_on_home: true
  show_in_contact: false
linkedin:
  url: https://www.linkedin.com/in/rutvora
  show_on_home: true
  show_in_contact: false
slack:
  url:
  show_on_home: true
  show_in_contact: false
blog:
  url: https://rutvora.blogspot.com
  show_on_home: true
  show_in_contact: false
youtube:
  url: https://www.youtube.com/channel/UCLaHH4xiZZADIYZ-SwTtY2w
  show_on_home: true
  show_in_contact: false

# Social Links
facebook:
  url: https://www.facebook.com/rutvora/
  show_on_home: false
  show_in_contact: true
googleplus:
  url:
  show_on_home: false
  show_in_contact: true
instagram:
  url: https://instagram.com/rutvora
  show_on_home: false
  show_in_contact: true
pinterest:
  url:
  show_on_home: false
  show_in_contact: true
twitter:
  url:
  show_on_home: false
  show_in_contact: true

# Build settings
markdown: kramdown

sass:
style: compressed

# Work Timeline
work:
  - company: "<a href=\"https://systopia.cs.ubc.ca/\">Systopia Lab @ UBC CS</a>"
    details:
      - date: "Sep '22 - "
        position: "Research Assistant"
        description: >
          Researching on mitigating network side channel attacks using Differential Privacy
  - company: "<a href=\"https://f5.com\">F5, Inc.</a>"
    details:
      - date: "Apr '22 - Aug '22"
        position: "Software Engineer II"
        description: >
          1. Worked with eBPF for System Call Tracing in a Platform-as-a-service Environment <br />
          2. Worked with P4lang for injecting proprietary information in SRv6 headers

      - date: "Sep '20 - Apr '20"
        position: "Software Engineer I"
        description: >
          1. Worked with WebAssembly and WebAssembly System Interface to create re-usable modules for F5 products <br />
          2. Created PoC to enable unmodified apps to use DPDK and F-Stack (deployed on SmartNICs)
  - company: "Ericsson"
    details:
      - date: "Jul '19 - Dec '19"
        position: "Research Intern"
        description: >
          1. Published a <a href="https://doi.org/10.1201/9781003052098-34">research Paper</a> on 5G connectivity solution in Hyperloop <br />
          2. Proposed architectures for implementing 5G in AR/VR, Home Automation etc.

# Projects Timeline
# Note: The <style> in Work is somehow also applied to Projects! So no need to apply again in the file
projects:
  - title: "Adaptive Video Streaming on UDP"
    date: "Apr '19 - Jun '19"
    description: "Dynamically determine video compression factors like spatial and temporal compression, rate factors and codecs"
    link: "https://github.com/rutvora/Intranet-Video-Caller/tree/master/GoLang/Video%20Caller"
  - title: "Firmware Verification/Update in IoT devices using Ethereum Blockchain"
    date: "Mar '19 - Apr '19"
    description: "Proposed architecture to verify firmware integrity in IoT devices (similar to \"Secure Boot\") using Smart Contracts on Ethereum"
    link: "https://github.com/RUTVORA/FIRMWARE_VERIFICATION-UPDATE_WITH_SMART_CONTRACTS"
  - title: "Communication without the Internet"
    date: "Oct '18"
    description: "Enabled communicating safety status of user during a natural disaster using Bluetooth/Wifi-Direct"
  - title: "Natural Disaster NavIC"
    date: "Feb '19"
    description: "Utilised 200-bit space in NavIC (Indian GPS counterpart) transmissions to send 10 safe locations and their status with 100m accuracy during a natural disaster (as a part of an ISRO hackathon)"
