# Site settings
title: Dimension
email: youremailaddress@gmail.com
description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon
remote_theme: andrewbanchich/dimension-jekyll-theme

# Research Links
orcid_url: https://orcid.org/0000-0001-5064-1760
googlescholar_url: https://scholar.google.com/citations?user=gB4ZP1MAAAAJ
researchgate_url: https://www.researchgate.net/profile/Rut-Vora

# Work Links
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
slack_url:
blog_url: https://rutvora.blogspot.com
youtube_url: https://www.youtube.com/channel/UCLaHH4xiZZADIYZ-SwTtY2w

# Social Links
facebook_url:
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
pinterest_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

sass:
style: compressed

# Work Timeline
work:
  - company: "Some company"
    details:
      - date: "October 2022"
        position: "Your position"
        description: "Some description"
      - date: "June 2022"
        position: "Different Position"
        description: "Different Description"
  - company: "Some other company"
    details:
      - date: "October 2020"
        position: "Your position"
        description: "Some description"
      - date: "June 2020"
        position: "Different Position"
        description: "Different Description"

# Projects
# Note: The <style> in Work is somehow also applied to Projects! So no need to apply again in the file
projects:
  - title: "Project 1"
    date: "Some date"
    description: "Some description"
    link: "https://github.com/rutvora/rutvora.github.io"
  - title: "Project 2"
    date: "Some other date"
    description: "Some other description"
