# Site settings
title: Dimension
email: 
  id: youremailaddress@gmail.com
  show_on_home: true
  show_in_contact: true
description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon
remote_theme: andrewbanchich/dimension-jekyll-theme

# Email show config

# Research Links
orcid: 
  url: https://orcid.org/0000-0001-5064-1760
  show_on_home: true
  show_in_contact: false
googlescholar: 
  url: https://scholar.google.com/citations?user=gB4ZP1MAAAAJ
  show_on_home: true
  show_in_contact: false
researchgate: 
  url: https://www.researchgate.net/profile/Rut-Vora
  show_on_home: true
  show_in_contact: false

# Work Links
github: 
  url: https://www.github.com/rutvora
  show_on_home: true
  show_in_contact: false
gitlab: 
  url: 
  show_on_home: true
  show_in_contact: false
linkedin: 
  url: https://www.linkedin.com/in/rutvora
  show_on_home: true
  show_in_contact: false
slack:
  url:
  show_on_home: true
  show_in_contact: false
blog: 
  url: https://rutvora.blogspot.com
  show_on_home: true
  show_in_contact: false
youtube: 
  url: https://www.youtube.com/channel/UCLaHH4xiZZADIYZ-SwTtY2w
  show_on_home: true
  show_in_contact: false

# Social Links
facebook:
  url: 
  show_on_home: false
  show_in_contact: true
googleplus:
  url: 
  show_on_home: false
  show_in_contact: true
instagram:
  url: 
  show_on_home: false
  show_in_contact: true
pinterest:
  url: 
  show_on_home: false
  show_in_contact: true
twitter:
  url: 
  show_on_home: false
  show_in_contact: true

# Build settings
markdown: kramdown

sass:
style: compressed

# Work Timeline
work:
  - company: "Some company"
    details:
      - date: "October 2022"
        position: "Your position"
        description: "Some description"
      - date: "June 2022"
        position: "Different Position"
        description: "Different Description"
  - company: "Some other company"
    details:
      - date: "October 2020"
        position: "Your position"
        description: "Some description"
      - date: "June 2020"
        position: "Different Position"
        description: "Different Description"

# Projects Timeline
# Note: The <style> in Work is somehow also applied to Projects! So no need to apply again in the file
projects:
  - title: "Project 1"
    date: "Some date"
    description: "Some description"
    link: "https://github.com/rutvora/rutvora.github.io"
  - title: "Project 2"
    date: "Some other date"
    description: "Some other description"
